[info]
type_name = "std::array"
ctype = "ARRAY_TYPE"
header = "array"

# Old:
numTemplateParams = 1
ns = ["namespace std"]
typeName = "std::array<"

[codegen]
decl = """
template<typename T, long unsigned int N>
void getSizeType(const %1%<T, N> &container, size_t& returnArg);
"""

func = """
template<typename T, long unsigned int N>
void getSizeType(const %1%<T,N> &container, size_t& returnArg)
{
    SAVE_DATA((uintptr_t)container.size());
    SAVE_SIZE(sizeof(container));

    for (auto & it: container) {
        // undo the static size that has already been added per-element
        SAVE_SIZE(-sizeof(it));
        getSizeType(it, returnArg);
    }
}
"""
