[info]
type_name = "folly::Optional"
ctype = "FOLLY_OPTIONAL_TYPE"
header = "folly/Optional.h"

# Old:
typeName = "folly::Optional<"
ns = ["folly::Optional"]
numTemplateParams = 1
replaceTemplateParamIndex = []

[codegen]
decl = """
template<typename T>
void getSizeType(const %1%<T> &container, size_t& returnArg);
"""

func = """
template <typename T>
void getSizeType(const %1%<T>& container, size_t& returnArg) {
  if (container) {
    SAVE_SIZE(sizeof(%1%<T>) - sizeof(T));
    SAVE_DATA((uintptr_t)(container.get_pointer()));

    getSizeType(*(container.get_pointer()), returnArg);
  } else {
    SAVE_SIZE(sizeof(%1%<T>));
    SAVE_DATA(0);
  }
}
"""
