[info]
type_name = "std::pair"
ctype = "PAIR_TYPE"
header = "utility"

# Old:
typeName = "std::pair<"
ns = ["namespace std"]
numTemplateParams = 2
replaceTemplateParamIndex = []

[codegen]
decl = """
template<typename P, typename Q>
void getSizeType(const %1%<P,Q> &container, size_t& returnArg);
"""

func = """
template<typename P, typename Q>
void getSizeType(const %1%<P,Q> &container, size_t& returnArg)
{
    SAVE_SIZE(sizeof(%1%<P,Q>) - sizeof(P) - sizeof(Q));

    getSizeType(container.first, returnArg);
    getSizeType(container.second, returnArg);
}
"""
