[info]
type_name = "std::reference_wrapper"
ctype = "REF_WRAPPER_TYPE"
header = "functional"

# Old:
typeName = "std::reference_wrapper<"
ns = ["namespace std"]
numTemplateParams = 1
replaceTemplateParamIndex = []

[codegen]
decl = """
template<typename T>
void getSizeType(const %1%<T> &ref, size_t& returnArg);
"""

func = """
template<typename T>
void getSizeType(const %1%<T> &ref, size_t& returnArg)
{
    SAVE_SIZE(sizeof(%1%<T>));
    SAVE_DATA((uintptr_t)&(ref.get()));
    if (ctx.pointers.add((uintptr_t)&ref.get())) {
        SAVE_DATA(1);
        getSizeType(ref.get(), returnArg);
    } else {
        SAVE_DATA(0);
    }
}
"""
