[info]
type_name = "std::unordered_map"
stub_template_params = [2,3,4]
ctype = "STD_UNORDERED_MAP_TYPE"
header = "unordered_map"

# Old:
typeName = "std::unordered_map<"
ns = ["namespace std"]
numTemplateParams = 2
replaceTemplateParamIndex = [2, 3]
allocatorIndex = 4

[codegen]
decl = """
template<class K, class T, class H, class KE, class A>
void getSizeType(const %1%<K, T, H, KE, A> &container, size_t& returnArg);
"""

func = """
template<class K, class T, class H, class KE, class A>
void getSizeType(const %1%<K, T, H, KE, A> &container, size_t& returnArg)
{
    constexpr size_t nodeSize = sizeof(typename %1%<K, T, H, KE, A>::node_type);
    size_t bucketCount = container.bucket_count();
    size_t numElems = container.size();

    SAVE_SIZE(sizeof(%1%<K, T, H, KE, A>) + (nodeSize * numElems) + (bucketCount * sizeof(uintptr_t)));

    SAVE_DATA((uintptr_t)nodeSize);
    SAVE_DATA((uintptr_t)bucketCount);
    SAVE_DATA((uintptr_t)numElems);

    for (auto const& it : container)
    {
      getSizeType(it.first, returnArg);
      getSizeType(it.second, returnArg);
    }
}
"""

handler = """
template <typename DB, typename T0, typename T1, typename T2, typename T3, typename T4>
struct TypeHandler<DB, %1%<T0, T1, T2, T3, T4>> {
  using type = types::st::Pair<DB,
      types::st::VarInt<DB>,
      types::st::Pair<DB,
        types::st::VarInt<DB>,
        types::st::List<DB, types::st::Pair<DB,
          typename TypeHandler<DB, T0>::type,
          typename TypeHandler<DB, T1>::type
    >>>>;

  static types::st::Unit<DB> getSizeType(
      const %1%<T0, T1, T2, T3, T4>& container,
      typename TypeHandler<DB, %1%<T0, T1, T2, T3, T4>>::type returnArg) {
    constexpr size_t nodeSize = sizeof(typename %1%<T0, T1, T2, T3, T4>::node_type);

    auto tail = returnArg.write(nodeSize)
                    .write(container.bucket_count())
                    .write(container.size());

    // The double ampersand is needed otherwise this loop doesn't work with
    // vector<bool>
    for (const auto& it : container) {
      tail = tail.delegate([&it](auto ret) {
        return OIInternal::getSizeType<DB>(it.second, ret.delegate([&it](auto ret) {
            return OIInternal::getSizeType<DB>(it.first, ret);
        }));
      });
    }

    return tail.finish();
  }
};
"""

traversal_func = """
auto tail = returnArg
  .write((uintptr_t)&container)
  .write(container.bucket_count())
  .write(container.size());

for (const auto& kv : container) {
  tail = tail.delegate([&kv](auto ret) {
    auto start = maybeCaptureKey<captureKeys, DB, T0>(kv.first, ret);
    auto next = start.delegate([&kv](typename TypeHandler<DB, T0>::type ret) {
      return OIInternal::getSizeType<DB>(kv.first, ret);
    });
    return OIInternal::getSizeType<DB>(kv.second, next);
  });
}

return tail.finish();
"""

[[codegen.processor]]
type = "types::st::VarInt<DB>"
func = """
el.pointer = std::get<ParsedData::VarInt>(d.val).value;
"""

[[codegen.processor]]
type = "types::st::VarInt<DB>"
func = """
// Using the container's capacity to temporarily store the number of buckets
// TODO: Is there another way to pass a value across processors?
el.container_stats.emplace(result::Element::ContainerStats {
  .capacity = std::get<ParsedData::VarInt>(d.val).value,
});
"""

[[codegen.processor]]
type = """
std::conditional_t<captureKeys,
 types::st::List<DB,
   types::st::Pair<DB,
     typename CaptureKeyHandler<DB, T0>::type,
     types::st::Pair<DB,
       typename TypeHandler<DB, T0>::type,
       typename TypeHandler<DB, T1>::type>>>,
 types::st::List<DB, types::st::Pair<DB,
   typename TypeHandler<DB, T0>::type,
   typename TypeHandler<DB, T1>::type>>
>
"""
func = """
#ifdef __GLIBCXX__
/* Use libstdc++ implementation __details to compute the size of Nodes and Buckets.
 *
 * See the source of <bits/hashtable_policy.h>:
 * https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00536_source.html
 */
using OI_value_type = std::pair<const T0, T1>;
using OI_Hash_node =
  std::__detail::_Hash_node<
    OI_value_type,
    std::__cache_default<OI_value_type, T2>::value>;

using OI_bucket = std::__detail::_Hash_node_base;

static constexpr size_t element_size = sizeof(OI_Hash_node);
static constexpr size_t bucket_size = sizeof(OI_bucket);
#else
static_assert(false && "No known element_size for sets. See types/set_type.toml");
#endif

auto list = std::get<ParsedData::List>(d.val);
// Reading the bucket count that was stored in `capacity` by the processor above.
size_t bucket_count = el.container_stats->capacity;
el.exclusive_size += bucket_count * bucket_size;
el.exclusive_size += list.length * (element_size - sizeof(T0));

// Overwrite the bucket count stored in `capacity` with the actual container's values.
el.container_stats.emplace(result::Element::ContainerStats {
  .capacity = list.length,
  .length = list.length,
});

static constexpr std::array<inst::Field, 2> element_fields{
  make_field<DB, T0>("key"),
  make_field<DB, T1>("value"),
};

static constexpr auto processors = maybeCaptureKeysProcessor<captureKeys, DB, T0>();

static constexpr auto element = inst::Field{
  element_size,
  element_size - sizeof(T0) - sizeof(T1),
  "[]",
  std::array<std::string_view, 0>{},
  element_fields,
  processors,
};

for (size_t i = 0; i < list.length; i++)
  stack_ins(element);
"""
