[info]
type_name = "folly::Try"
ctype = "TRY_TYPE"
header = "folly/Try.h"

# Old:
typeName = "folly::Try<"
ns = ["folly::Try"]
numTemplateParams = 1
replaceTemplateParamIndex = []

[codegen]
decl = """
template<typename T>
void getSizeType(const %1%<T> &container, size_t& returnArg);
"""

func = """
template<typename T>
void getSizeType(const %1%<T> &container, size_t& returnArg)
{
    SAVE_SIZE(sizeof(%1%<T>));
    SAVE_DATA((uintptr_t)&container);
    if (container.hasValue()) {
        SAVE_DATA((uintptr_t)(&(container.value())));
        getSizeType(container.value(), returnArg);
    } else {
        SAVE_DATA(0);
    }
}

/* Workaround for issue https://github.com/facebookexperimental/object-introspection/issues/289 */
extern "C" void _ZNSt11logic_errorC2EOS_(void) {}
"""
